# Generated by Django 4.1.7 on 2023-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300, null=True)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("create_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                ("person_name", models.CharField(max_length=255)),
                ("person_birth_date", models.DateField(null=True)),
                ("person_arrest_date", models.DateField(null=True)),
                ("person_death_date", models.DateField(null=True)),
                ("mem_book_note", models.TextField(null=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="images", to="persons.imageurl"
                    ),
                ),
            ],
        ),
    ]
