# Generated by Django 4.1.7 on 2023-03-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="images", to="persons.imageurl"
            ),
        ),
    ]
