# Generated by Django 4.1.7 on 2023-04-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_alter_person_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="imageurl",
            name="url",
        ),
        migrations.AddField(
            model_name="imageurl",
            name="image",
            field=models.ImageField(null=True, upload_to="images"),
        ),
    ]
